<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ND8J206" failures="4" tests="40" name="Com.Cen.TestCases.diagnosis" time="320.179" errors="0" timestamp="2022-05-19T13:00:58 IST" skipped="0">
  <testcase classname="Com.Cen.TestCases.diagnosis" name="verify_invalidEmail" time="11.131"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="login_With_Invalid" time="15.932"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_HamburgarMenu" time="15.190"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="diagnosis_Click" time="5.138"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="verifyDiagnosis" time="11.063"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="aad_Domain_Click" time="5.128"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="verifyAddDomainPopup" time="10.053"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cross_ButtonAddDomain" time="5.103"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cancel_ButtonAddDomain" time="5.233"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_DiaDomainName" time="5.499"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="type_DiaDomainName" time="5.260"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cross_DiaDomainName" time="10.102"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="blank_DiaDomaninName" time="5.048"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="numeric_DiaDomaninName" time="5.159">
    <failure message="The following asserts failed:
	expected [The Diagnosis Domain Name field is required] but found [The Diagnosis Domain Name must be valid]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [The Diagnosis Domain Name field is required] but found [The Diagnosis Domain Name must be valid]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Com.Cen.TestCases.diagnosis.numeric_DiaDomaninName(diagnosis.java:164)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- numeric_DiaDomaninName -->
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="onlySymbol_DiaDomaninName" time="5.215">
    <failure message="The following asserts failed:
	expected [The Diagnosis Domain Name field is required] but found [The Diagnosis Domain Name must be valid]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [The Diagnosis Domain Name field is required] but found [The Diagnosis Domain Name must be valid]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Com.Cen.TestCases.diagnosis.onlySymbol_DiaDomaninName(diagnosis.java:182)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- onlySymbol_DiaDomaninName -->
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_DiaDomainHidden" time="5.112"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="save_ButtonAddDomain" time="15.360"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_AddGroup" time="5.123"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="verifyAddDiagnosisGroupPopup" time="10.050"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cross_ButtonAddDomainGroup" time="5.073"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cancel_ButtonAddGroup" time="10.174"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_DiaGroupName" time="10.172"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="type_DiagroupName" time="5.144"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cross_DiaGroupName" time="5.080"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="blank_DiaGroupName" time="5.057"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="numeric_DiagroupName" time="10.142">
    <failure message="The following asserts failed:
	expected [The Diagnosis Group Name field is required] but found [The Diagnosis Group Name must be valid]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [The Diagnosis Group Name field is required] but found [The Diagnosis Group Name must be valid]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Com.Cen.TestCases.diagnosis.numeric_DiagroupName(diagnosis.java:387)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- numeric_DiagroupName -->
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="symbol_DiagroupName" time="10.214">
    <failure message="The following asserts failed:
	expected [The Diagnosis Group Name field is required] but found [The Diagnosis Group Name must be valid]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [The Diagnosis Group Name field is required] but found [The Diagnosis Group Name must be valid]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Com.Cen.TestCases.diagnosis.symbol_DiagroupName(diagnosis.java:405)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- symbol_DiagroupName -->
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_DiaGroupActive1" time="10.114"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="save_ButtonAddGroup" time="15.351"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_DiaGroupActive" time="5.103"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="tDotDiaDomain" time="5.158"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="verifyManageDiaDomainPopup" time="10.059"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="ManDiaDomainhidden" time="5.096"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="ManDiaDomaincross" time="5.104"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cancel_ButtonManDiaDomName" time="10.196"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="click_ManDiaName" time="10.195"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="type_ManDiaName" time="5.379"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="cross_ManDiaDomaninField" time="5.088"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="blank_ManDiaDomName" time="6.049"/>
  <system-out/>
  <testcase classname="Com.Cen.TestCases.diagnosis" name="save_ButtonManDiaDomName" time="10.332"/>
  <system-out/>
</testsuite> <!-- Com.Cen.TestCases.diagnosis -->
